spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/e-commerce?useSSL=false
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: '8082'
